version: '3.8'
services:

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 16379:6379
    volumes: 
      - redis:/data
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
  sqs:
    image: softwaremill/elasticmq
    restart: unless-stopped
    ports:
      - 9324:9324
      - 9325:9325
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kyoo
      MYSQL_DATABASE: kyoo
    ports:
      - 60333:3306

volumes:
  redis:
    driver: local